### ISSUE TITLE
Cause Execution failed for task ':expo-application:compileReleaseKotlin'.

### ISSUE THREAD

**Issue by linonetwo** [Nonononoki/expo-location#1]
```

> Task :expo-modules-core:compileReleaseJavaWithJavac
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :expo-modules-core:bundleLibCompileToJarRelease
> Task :react-native-reanimated:configureCMakeRelWithDebInfo[x86]
> Task :expo-application:compileReleaseKotlin FAILED

396 actionable tasks: 391 executed, 5 up-to-date
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':expo-application:compileReleaseKotlin'.
> 'compileReleaseJavaWithJavac' task (current target is 17) and 'compileReleaseKotlin' task (current target is 11) jvm target compatibility should be set to the same Java version.
  Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain

```

https://github.com/tiddly-gittly/TidGi-Mobile/actions/runs/7833780879/job/21375553710

---

Even only add expo-application from https://github.com/Nonononoki/expo-application get the same way... How did you build your APP? Mine is https://github.com/tiddly-gittly/TidGi-Mobile/blob/master/.github/workflows/build-f-droid-apk.yml

**Comment by Nonononoki** [comment]
The expo version has to match exactly. You're already using expo 50, I'm still on 49. You either need to downgrade, create a PR or wait until I update the libraries.

**Comment by linonetwo** [comment]
Thanks, so it is to imply update the version number? I didn't see where to put it. And how do you debug it? Just prebuild locally and `./gradle xxx` to see if there is an error? 

I have another question, in expo, is it only location and application package needs replacement? I also install `expo-barcode-scanner` and `withAndroidShareExtension` https://github.com/tiddly-gittly/TidGi-Mobile/blob/c623b263625be4c8eb8c03397a429b2887097c08/app.json#L43 
Do you think they also need something like this?

**Comment by Nonononoki** [comment]
You need to get the source code of the version you need and strip the Google code. No idea how to debut it, maybe ask on the expo repo.
